server:
  port: 8081
  servlet:
    context-path: /api

arb-rpc: wss://arb-sepolia.g.alchemy.com/v2/mzRwv-ctDBaqMDYVCxRX-3H-owXm3Z5S
contract-address: "0x53D4F62Ddf0bE196771820Ff1Ec6E30834da0eDb"
ERC20_CONTRACT_ADDRESS: "0x93e519bf6b9a0d0fd239dd02ed8c678d26e3979e"
private_key: "4eeaec53e6e2525c5b956ce3af50e695a2ae29fcf13acd6378408e1124c88ef2"


spring:
  application:
    name: decentralized_video_platform_server
  datasource:
    datatype: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/decentralized_video_platform_db?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 2002
    druid:
      initial-size: 1
      min-idle: 1
      max-wait: 6000
      max-active: 20
  web:
    cross-domain:
      enabled: true
      allowed-origins: 'http://localhost:8080'
      allowed-methods: GET, POST, PUT, DELETE, OPTIONS
      allow-credentials: true
      allowed-headers: '*'
  redis:
    host: localhost
    port: 6379
    database: 0
mybatis-plus:
  global-config:
    enable-sql-runner: true
logging:
  level:
    root: INFO
  file:
    name: ./logs/decentralized-video-platform.log